### ISSUE TITLE
notes as jupyter notebooks?

### ISSUE THREAD

**Issue by miwojc** [hiromis/notes#12]
Hi Hiromi
First of all big thank you for the work you did and effort you put into making the notes. They are so detailed and helped so many students to learn Deep Learning. I've seen them used everywhere!

Just a suggestion. What if the notes where in jupyter notebook format so that the incorporated code can be run for example at Google colab, kaggle kernels or locally? Jupyter files can be viewed at github anyway if someone don't want to run the code, just read.

just an idea...

Keep up the good work!

**Comment by hiromis** [comment]
Hello @miwojc
I'm glad and thank you for your kind words :)

Yes, I did contemplate with that idea before I started version 3 of the class. The challenge has been that Jeremy sometimes go over the notebook from the bottom to the top or sometimes jump to spreadsheet in the middle of the notebook, so if I were to do that in Jupyter notebook, the transcription makes sense but the code doesn't run, or vice versa. Currently, there are discussion about collaborative notes for part 2 in the forum, and it will be either markdown or jupyter notebook. I guess we'll see what people decide on.

Thank you for the suggestion!
